//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IMod")]
    public interface IMod {
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.None, Action="http://tempuri.org/IMod/Add", ReplyAction="http://tempuri.org/IMod/AddResponse")]
        void Add(string name, int age, bool isStudent);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.None, Action="http://tempuri.org/IMod/Add", ReplyAction="http://tempuri.org/IMod/AddResponse")]
        System.Threading.Tasks.Task AddAsync(string name, int age, bool isStudent);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.None, Action="http://tempuri.org/IMod/GetList", ReplyAction="http://tempuri.org/IMod/GetListResponse")]
        string GetList();
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.None, Action="http://tempuri.org/IMod/GetList", ReplyAction="http://tempuri.org/IMod/GetListResponse")]
        System.Threading.Tasks.Task<string> GetListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IModChannel : WcfClient.ServiceReference3.IMod, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModClient : System.ServiceModel.ClientBase<WcfClient.ServiceReference3.IMod>, WcfClient.ServiceReference3.IMod {
        
        public ModClient() {
        }
        
        public ModClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Add(string name, int age, bool isStudent) {
            base.Channel.Add(name, age, isStudent);
        }
        
        public System.Threading.Tasks.Task AddAsync(string name, int age, bool isStudent) {
            return base.Channel.AddAsync(name, age, isStudent);
        }
        
        public string GetList() {
            return base.Channel.GetList();
        }
        
        public System.Threading.Tasks.Task<string> GetListAsync() {
            return base.Channel.GetListAsync();
        }
    }
}
